### ISSUE TITLE
cli command: wp redipress delete not working after 2.0 update

### ISSUE THREAD

**Issue by Liblastic** [devgeniem/redipress#136]
Example error:

wp redipress delete --post_type=page --blog_id=3 --limit=500
PHP Fatal error:  Uncaught Error: Cannot unset string offsets in plugins/redipress/src/CLI/Delete.php:110
Stack trace:

**Comment by HPiirainen** [comment]
Fixed via 0ce652138256a01dc9bfd804487e54f4410bcb94 and changes documented to README.
